### ISSUE TITLE
US1: List of Routes

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#1]
## Value Proposition

As a user  
I want to see the list of available routes 
so that I can browse through them.
​

## Description

![image](https://github.com/Dariastep/capstone-project/assets/123622878/bf144739-701c-40da-b38a-abee6ae99570)

## Acceptance Criteria

- [x] I am able see a list of hiking routes.
- [x] I am able to see the heading of the hiking routes.
- [x] The Heading is fixed on the top of the screen.
- [x] Each route is displayed with its name, photo and the basic information.
- [x] The list is scrollable (if there are more routes than can fit on the screen).​

## Tasks

- [x] Set up the project using next.js
- [x] Create a repo in GitHub and connect it to the project
- [x] Create a new branch "route_list_feature"
- [x] Create a dummy data array with the hike relevant infos: name, activity, difficulty level, length, altitude.
- [x] Create a component "RouteList"
- [x] Pass the dummy data array as props to the "RouteList" 
- [x] In the "RouteList" component map over the data props and render each route as a list item with the relevant infos (s.above)
- [x] Apply some basic CSS to make the "RouteList" readable.
- [x] Write some tests for the "RouteList". 
      ​

**Comment by julialoeschel** [comment]
Hey, 
that is a great first story, I have nothing to add! 

good job!

**Comment by ghost** [comment]
i think that would work
