### ISSUE TITLE
US8: Profile Page Edit

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#10]
## Value Proposition

As a user,
I want to have a profile page,
so that I can update my personal information.
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/f2bd7acc-1ed6-4835-970b-0c13ed0d26ad)

## Acceptance Criteria

- [ ] The user should be able to update their profile information, such as name, email, and profile picture.
- [ ] Changes made to the profile information should be saved in the local storage.

## Tasks

- [ ] Create a new branch named "profile_page__editing_feature"
- [ ] Implement form fields for updating the profile information, such as name and email.
- [ ] Include an image upload functionality (Cloudinary) for updating the profile picture.
- [ ] The form for the profile information fields should have rules to ensure the name and email fields are filled out correctly.
- [ ] The form for the profile information fields should display error message, if the input does not meet the validation criteria.
- [ ] Implement a function to handle the form submit event.
- [ ] Update the user's profile information in the local state.
- [ ] Update the local storage with the new profile information when it is successfully updated.
- [ ] Apply some basic CSS to the form.
- [ ] Write some test for the form.

**Comment by Danielschuetzle** [comment]
LGTM

**Comment by MariaRiosNavarro** [comment]
It seems little, but a lot of work in a single US (new page, form, validation, storage, claudinary..) but it is all related and makes sense. Very detailed tasks. I like it very much and it helps to understand how you are going to do it. It seems very interesting. 🚀
