### ISSUE TITLE
US6: Profile Page (create)

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#11]
## Value Proposition

As a user,
I want to have a profile page,
so that I can see my personal information.
​

## Description

![Image](https://user-images.githubusercontent.com/123622878/250059629-3b9d7070-86ee-4615-b0c0-e54b9673fefc.png)

## Acceptance Criteria

- [ ] The app should have a profile page.
- [ ] The profile should have a heading "My Profile".
- [ ] The profile page should display the user's name, profile picture, and other relevant information.
- [ ] Clicking on a navigation link "My Profile" should navigate the user to this  page.
- [ ] The active link My Profile" in the navigation bar should be visually highlighted to indicate the current page.
- [ ] I can click on a "Back" button that allows to navigate back to the previous page.

## Tasks

- [ ] Create a new branch named "profile_page_feature"
- [ ] Create a ProfilePage component which renders elements for displaying the user's name, profile picture, and other relevant information.
- [ ] Create a page "profile page" and add the routing.
- [ ] Implement the "My Profile" navigation link.
- [ ] Implement the "Back" button.
- [ ] Apply some basic CSS to make the "My Profile" readable.
- [ ] Write some tests for the "My Profile".

**Comment by matschi3** [comment]
LGTM 🚀 go for it
