### ISSUE TITLE
US9: Upload Profile Image (Cloudinary)

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#15]
## Value Proposition

As a user,
I want to be able upload a profile image,
so that I can make my account more personal
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/f2bd7acc-1ed6-4835-970b-0c13ed0d26ad)

## Acceptance Criteria

- [ ] The user should be able to select and upload an image file for their profile picture.
- [ ] The uploaded profile picture should be saved and associated with the user's account.
- [ ] The user's profile page should display their uploaded profile picture.

## Tasks

- [ ] Create a new branch named "upload_image_feature"
- [ ] Add a file input field to the Profile form component to allow the user to select an image file for their profile picture.
- [ ] Implement an image upload functionality using Cloudinary API.
- [ ] Include an upload the selected image file to Cloudinary to the function Handlesubmit in the form.
- [ ] Update the backend API route to receive the uploaded image URL from Cloudinary
- [ ] Apply some basic CSS to the form.
- [ ] Write some test for the form.

**Comment by CarstenJahnke** [comment]
Looks very well 😀
