### ISSUE TITLE
US10: Create a route

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#16]
## Value Proposition

As a user,
I want to be able to create my own routes,
so that I can enjoy my self-created routes.
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/907a970e-ec07-430d-b21d-53711d89ff99)

## Acceptance Criteria

- [x] "My Routes" should be visible on all pages in the Navigation Bar.
- [x] Clicking on the "My Routes" link should redirect the user to a page that displays their created routes, or a message "No routes are created yet".
- [x] The "My Routes" page should have a "Create a Route" button that leads to the route creation form.
- [x] The route creation form should have all the necessary fields (name, region, activity, difficulty, length, altitude, description, and image upload) and allow the user to enter the required information.
- [x] Submitting the route creation form should save the route to the database and display it in the "My Routes" page.

## Tasks

- [x] Create a new branch named "create_route_feature".
- [x] Add the new page "My Routes"that shows a list of routes created by the current user.
- [x] Add a "Create a Route" button to the "My Routes" page.
- [x] Create a route creation form with fields for name, region, activity, difficulty, length, altitude, description, and an image upload (Clodinary, optional).
- [x] Implement the functionality to submit the route creation form and save the newly created route to the MongoDB database.
- [x] Display the newly created route in the "My Routes" page after successful submission.
- [x] Apply some basic CSS to the form.
- [x] Write some test for the form.

**Comment by DErdmann1** [comment]
Super detailed! Looks good :) 👍
