### ISSUE TITLE
US11: Delete a route

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#17]
## Value Proposition

As a user, 
I want to be able to delete routes that I have created, 
so that I can  remove any routes that I no longer need.
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/92f82b76-6b69-4f94-a13f-9296ff1f516e)

## Acceptance Criteria

- [ ] "My Routes" should be visible on all pages in the Navigation Bar.
- [ ] Clicking on the "My Routes" link should redirect the user to a page that displays their created routes, or a message "No routes are created yet".
- [ ] The "My Routes" page should have a "Create a Route" button that leads to the route creation form.
- [ ] The route creation form should have all the necessary fields (name, region, activity, difficulty, length, altitude, description, and image upload) and allow the user to enter the required information.
- [ ] Submitting the route creation form should save the route to the database and display it in the "My Routes" page.

## Tasks

- [ ] Create a new branch named "delete_route_feature".
- [ ] Add a "delete a Route" button to the details page of the self-created routes on "My Routes" page.
- [ ] Create an API endpoint or function to handle the route deletion request and remove the route from the database.
- [ ] Update the "My Routes" page to reflect the changes and remove the deleted route from the list.
- [ ] Handle the errors which may occur during the deletion process.
- [ ] Apply some basic CSS to the feature.
- [ ] Write some test for the feature.

**Comment by CarstenJahnke** [comment]
Looks so good Daria 😊🙏🏻
