### ISSUE TITLE
US12: Update a route

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#18]
## Value Proposition

As a user,
 I want to be able to edit the routes that I have created,
so that I can update the details of my routes when necessary.
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/3a3ec24f-574a-4eee-9708-850ee0fc1002)

## Acceptance Criteria

- [ ] Each detail page for routes created by the user have an edit button.
- [ ] Clicking on the edit button opens a form like by the creating a route where the user can modify the existing information.
- [ ] The form fields should be pre-filled with the current data of the route.
- [ ] After making the changes, the user should be able to submit the form to update the route information.
- [ ] The updated information should be saved to the database and reflected on the "My Routes" page.
- [ ] Any errors encountered during the editing process should be handled.

## Tasks

- [ ] Create a new branch named "update_route_feature".
- [ ] Add an edit button  to the detail page for routes that are created by the user.
- [ ] Implement a form (like the creation form with all nesessary fields).
- [ ] Create an API endpoint  to handle the route update request and save the modified route data to the database.
- [ ] Update the "My Routes" with all the changes and display the updated information for the edited route.
- [ ] Handle the possible error scenarios which may occur be the route editing.
- [ ] Apply some basic CSS to the form.
- [ ] Write some test for the form.

**Comment by CarstenJahnke** [comment]
Nice work 🤩👍
