### ISSUE TITLE
US2: Route details

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#2]
## Value Proposition

As a user, I
want to be able to view detailed information about a specific hiking route  on a separate page 
to understand more about the hike.
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/4596b065-0822-4efd-8fe4-505b686134ba)

## Acceptance Criteria

- [x] When I click on a route in the route list, the detailed information for that route should be displayed.
- [x] The detailed information should include the  Information, which is visible on the Routes List plus description,  photo.
- [x] When I am on the detailed Information view, I am able to come back to the Routes List.
- [x] The route details view should be accessible, following accessibility guidelines.
- [x] The list is scrollable (if there are more information than can fit on the screen).​

## Tasks

- [x] Create a new branch "route_details_feature"
- [x] Add in a  a dummy data array with the hike relevant infos: photo, description.
- [x] Create a component "RouteDetails"  display the detailed information of a route.
- [x] Set up a dynamic route in Next.js to handle the route details page
- [x] Import the sample data array containing the route information into the RouteDetails component.
- [x] Access the route details  from the RoutesData array.
- [x] Return the detailed information of the selected route within the RouteDetails component.
- [x] If the selected route does not exist or is invalid, the error message  should be shown on the page. 
- [x] Add the Button "back" to come back to the Routes List.
- [x] Apply some basic CSS to make the "RouteDetails" readable.
- [x] Write some tests for the "RouteDetails". 
      ​

**Comment by julialoeschel** [comment]
great story, verry detailed. 
only suggestion: leave the hint out completely -> map and weather coming soon. this is not necessary here and does not contribute to this userstory. 
wen dont need it on the scribble and not in the ACs 

:) :octocat:

**Comment by julialoeschel** [comment]
lgtm 🚀
