### ISSUE TITLE
US13: NextAuth implementing

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#21]
## Value Proposition

As a user, 
I want to be able to create my own account,
 so that I distinguish my routes from others and be able to edit and delete them.

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/a97015fe-895a-48f4-ac8c-a14ea7614529)

## Acceptance Criteria

- [ ] When logging in, users should be authenticated using NextAuth.
- [ ] The homepage should display the login mask. 
- [ ] if you logged in, you have a button "logout".
- [ ] if you are logged in, you can see the user-relevant in information.
- [ ] implement the protection logik so that the non-authorized user cannot see the user-relevant in information.

## Tasks

- [ ] Create a new branch named "nextAuth_feature".
- [ ] Implement NextAuth authentication in the app. (index.js)
- [ ] Check if we have session data (= user is already signed in => display a logout button)
- [ ] Apply some basic CSS to the form.
- [ ] Write some test for the form.

**Comment by ChristophLeuker** [comment]
LGTM! Go for it
