### ISSUE TITLE
US14: Weather API

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#24]
## Value Proposition

As a user,
 I want to be able to be informed about the weather in the region I will go,
so that I can be better prepared fo a hike.
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/23f813fd-a5df-4f37-94dc-51a47b8f0564)

## Acceptance Criteria

 
- [ ] The user can enter the region or location for which they want to get weather information.
- [ ] The system retrieves and displays the current weather conditions for the specified region, including temperature, humidity, wind speed, and weather description.
- [ ] The system provides a forecast of the upcoming weather, including temperature, weather description, and any predicted precipitation.
- [ ] The Weather forecast is displayed on the detail page.

## Tasks

- [ ] Create a new branch named "weather_feature".
- [ ] Set up the necessary weather data API integration.
- [ ] Implement the functionality to retrieve and parse weather data from the API based on the specified location.
- [ ] Implement the forecast functionality to display upcoming weather information.
- [ ] Implement the refresh functionality to update the weather information upon user request.
- [ ] Apply some basic CSS to the feature.
- [ ] Write some tests.

**Comment by josch87** [comment]
Nice feature! 

When getting the US from a PO I would have the following questions:
- ` The user can enter the region or location for which they want to get weather information.`
Where does the user enter the region or location? In his/her profile to tell the app where he/she is right now (GPS location...)? Or for each route on the routes edit page/modal? 
- `The system retrieves and displays the current weather conditions for the specified region, including temperature, humidity, wind speed, and weather description.`
Where is the weather information beeing displayed? On the routes detail page? I know that you say it in your last list item but in this acceptance criteria you already say that it needs to be displayed but without telling where. If it is the same here just delete "and displays" and add "Current weather and weather forecast are displayed on the detail page" for your last list item.
