### ISSUE TITLE
US14: Map API

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#25]
## Value Proposition

As a user,
I want to be able see the region I go for a hike on a map,
so that I can better understand the nearby area.
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/92f2324c-11c4-488c-8860-a4afc7e7a9ae)

## Acceptance Criteria

 
- [ ] The application should display a map on the screen.
- [ ] The map should show the region or area where the user plans to go for a hike.
- [ ] The map is displayed on the detail page.

## Tasks

- [ ] Create a new branch named "map_feature".
- [ ] Set up the necessary map data API integration.
- [ ] Implement the functionality to display the map on the screen.
- [ ] Apply some basic CSS to the feature.

**Comment by NilsOt1** [comment]
Cool feature!
One question: `The user can enter the region or location for which they want to get weather information.` Where does the user enter die location?

**Comment by Dariastep** [comment]
Thnk you for the review! Originally I wanted the implement this feature but since I changed my mind this will not be the part of the US. I deleted it now, thank you!

**Comment by ryliecc** [comment]
LGTM 🥳
