### ISSUE TITLE
US3: Favorite Button

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#3]
## Value Proposition

As a user, 
I want to be able to save my favorite hiking routes
so that later I can easily find the route.
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/d54bce20-0382-4faf-bfd5-e075389ba737)

## Acceptance Criteria

- [x] Each Route card on the RoutesList and also in the RouteDetails Page has a button which visually indicates a favorite button.
- [x] Clicking on the bookmark, I can see visually, that the favorite status of the corresponding route changed.
- [x] I can click on each favorite button  of each route and they shange their status independently from each other. 
- [x] I can clearly indicate whether a route is favorited or not.

 
## Tasks

- [x] Create a new branch "favorite_button_feature"
- [x] Add in a a dummy data array a "favorite" property for each route.
- [x] Create a component "FavoriteButton" to represent the button for favoriting a route.
- [x] Design  the FavoriteButton to visually indicate if the button is favorited or not (e.g.use svg).
- [x] Implement toggling of the favorite status of a route when the FavoriteButton is clicked.
- [x] Integrate the FavoriteButton component into the RouteList and the RouteDetails component to allow users to mark routes as favorites.
- [x] The favorite Status should be saved in the LocalStorage.
- [x] Apply some basic CSS for the "FavoriteButton".
- [x] Write some tests for the "FavoriteButton". 
      ​

**Comment by julialoeschel** [comment]
lgtm (looks good to me) 
:octocat: 
good story !
