### ISSUE TITLE
US4: Favorite Page

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#4]
## Value Proposition

As a user, I
I want to be able to view and manage my favorite hiking routes in the "Favorites" page,
so that I can keep all my favorites routes on one page.
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/e59e5e37-190a-4524-8900-e0665d2c78f1)

## Acceptance Criteria

- [x] on the Routes List page  and the RouteDetails Page I can see the link "Favorites".
- [x] Clicking on the the link "Favorites", I will be redirected to a Favorite Page.
- [x] On the Favorite Page I am able to see a list of my favorited routes.
- [x] If I didn't favorited any routes, I can see the following sentence on the Favorite Page: "you have no favorite routes yet".
- [x] I can see a button "Back" on the Favorite Page.
- [x] Clicking on the "Back" Button I will be redirected to the RoutesList Page.

## Tasks

- [x] Create a new branch "favorite_page_feature"
- [x] Create a component "FavoritePage"  to display all favorited routes.
- [x] Create a file "favoritesPage.js" under the "pages" directory.
- [x] Implement a link to the "Favorites" page on the Routes List and the Route Details page.
- [x] Implement routing so that clicking on the "Favorites" link redirects to the Favorite Page.
- [x] In the "FavoritePage" component display a list of favorited routes.
- [x]  If no routes are favorited, display the message "You have no favorite routes yet" on the Favorite Page.
- [x]  Implement a "Back" button on the Favorite Page.
- [x] Clicking the "Back" button should redirect back to the Routes List page.
- [x] Apply some basic CSS to make the "RouteDetails" readable.
- [x] Write some tests for the "RouteDetails".

**Comment by julialoeschel** [comment]
great.
on the scribble should be a "back" button, but it says "favorites"
anything else is fine for me. 
great job!

**Comment by Dariastep** [comment]
Hey, Julia, thank you! I
The Heading "Favorites" is related to the current page (Favorite page) and the "Back" button goes back to the Route List Page.
I changed the appearance oh the "back" button to show better that I am now on the Favorite Page. 
Is it now more clear?

**Comment by CarstenJahnke** [comment]
LGTM 😊
