### ISSUE TITLE
US7: Search Bar

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#8]
## Value Proposition

As a user, 
I want to be able to search for specific routes on the homepage 
so that I can quickly find the routes I'm interested in.
​

## Description

![Image](https://user-images.githubusercontent.com/123622878/249804911-3ed0e2c8-4acf-4511-9cc9-0d0311a57a41.png)

## Acceptance Criteria

- [ ] There should be a search bar displayed on the RouteList Page.
- [ ] The search bar should have an input field where the user can enter their search query and a button. 
- [ ] When the user submits the search query clicking on a button, the application should display the search results that match search query.
- [ ] Clearing the search query should reset the search results and display all available routes on the RouteList Page.
- [ ] The list is scrollable (if there are more information than can fit on the screen).​

## Tasks

- [x] Create a new branch "search_bar_feature"
- [x] Create the search bar component, which returns an input field  (live search).
- [x] Add the search bar component to the RouteList page
- [x] Implement state management for the search query and search results.
- [x] Display the search results on the RouteList page.
- [x] If the search query is cleared or empty, display all available routes.
- [x] If there are no matching results provide appropriate text to the user.
- [x] Apply some basic CSS to make the "SearchBar" readable.
- [x] Write some tests for the "SearchBar".

**Comment by Danielschuetzle** [comment]
LGTM 👍🏻
