### ISSUE TITLE
US5: Navigation Bar

### ISSUE THREAD

**Issue by Dariastep** [Dariastep/Lamo-hiking-app-capstone-project#9]
## Value Proposition

As a user,
I want to easily navigate through different pages of the website
so that I can easily access the desired page.
​

## Description

![Image](https://github.com/Dariastep/capstone-project/assets/123622878/c98d900d-e33b-4c2f-8b92-c63a851fd2ac)

## Acceptance Criteria

- [x] The navigation bar should be displayed at the bottom of each page.
- [x] The navigation bar should include the pages: Homepage (RouteList Page), Favorites, Profile.
- [x] Clicking on a navigation link should navigate the user to the corresponding page.
- [x] The active link in the navigation bar should be visually highlighted to indicate the current page.
- [x] The navigation bar should be accessible for screen readers.

## Tasks

- [x] Create a new branch "navigation_bar_feature"
- [x] Create the navigation bar component.
- [x] Add the navigation bar component to every page.
- [x] implement the routing logic for navigation.
- [x] Apply some basic CSS to make the "NavigationBar" readable.
- [x] Write some tests for the "NavigationBar".

**Comment by CarstenJahnke** [comment]
Love that Daria, very nice work and a good job! ☺️
